spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092
    topic: prod-topic
    group-id: group-1

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
test:
  topic: embedded-test-topic

