version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

#    ___________________________________________________________________________
#version: '2'
#services:
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#      ALLOW_ANONYMOUS_LOGIN: yes
#    ports:
#      - 22181:2181
#    networks:
#      - kafka
#
#  kafka:
#    image: 'bitnami/kafka:latest'
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    networks:
#      - kafka
#    ports:
#      - 29092:29092
#      - 9997:9997
#      - 9092:9092
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,EXTERNAL_SAME_HOST://localhost:29092,LISTENER_EXTERNAL://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_JMX_PORT: 9997
#      KAFKA_JMX_HOSTNAME: kafka

#  kafka-ui:
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - 8086:8080
#    environment:
#      DYNAMIC_CONFIG_ENABLED: true


#networks:
#  kafka:
#    driver: bridge

#    ___________________________________________________________________________
#version: '5.6'
#services:
#    zookeeper:
#       image: 'bitnami/zookeeper:latest'
#       environment:
#         ZOOKEEPER_CLIENT_PORT: 2181
#         ZOOKEEPER_TICK_TIME: 2000
#         ALLOW_ANONYMOUS_LOGIN: yes
#       ports:
#         - 22181:2181
#    kafka:
#        image: 'bitnami/kafka:latest'
#        depends_on:
#            - zookeeper
#        ports:
#            - 29092:29092
#            - 9997:9997
#        environment:
#            KAFKA_ADVERTISED_HOST_NAME: kafka
#            KAFKA_BROKER_ID: 1
#            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,HOST://localhost:9093
#            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,HOST:PLAINTEXT
#            KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,HOST://0.0.0.0:9093
#            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#            KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
#            KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
#            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#            KAFKA_JMX_PORT: 9997
#            KAFKA_JMX_HOSTNAME: kafka
#
#    kafka-ui:
#      container_name: kafka-ui
#      image: provectuslabs/kafka-ui:latest
#      ports:
#        - 8086:8080
#      environment:
#        DYNAMIC_CONFIG_ENABLED: true